//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package kr.ewhapp.kjw.handy.study;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import kr.ewhapp.handy.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ImageSelectFragment_
    extends ImageSelectFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;
    public final static String FLAG_ARG = "flag";
    public final static String URI_ARG = "uri";
    public final static String SUBJECT_ARG = "subject";
    public final static String STUDY_ARG = "study";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.layout_imagecheck, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectFragmentArguments_();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ImageSelectFragment_.FragmentBuilder_ builder() {
        return new ImageSelectFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        containerLayout = ((RelativeLayout) hasViews.findViewById(kr.ewhapp.handy.R.id.photo_container));
        photoIv = ((ImageView) hasViews.findViewById(kr.ewhapp.handy.R.id.photo_iv));
        {
            View view = hasViews.findViewById(kr.ewhapp.handy.R.id.photo_container);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ImageSelectFragment_.this.showDialog();
                    }

                }
                );
            }
        }
        init();
    }

    private void injectFragmentArguments_() {
        Bundle args_ = getArguments();
        if (args_!= null) {
            if (args_.containsKey(FLAG_ARG)) {
                flag = args_.getString(FLAG_ARG);
            }
            if (args_.containsKey(URI_ARG)) {
                uri = args_.getString(URI_ARG);
            }
            if (args_.containsKey(SUBJECT_ARG)) {
                subject = args_.getString(SUBJECT_ARG);
            }
            if (args_.containsKey(STUDY_ARG)) {
                study = args_.getString(STUDY_ARG);
            }
        }
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public ImageSelectFragment build() {
            ImageSelectFragment_ fragment_ = new ImageSelectFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

        public ImageSelectFragment_.FragmentBuilder_ flag(String flag) {
            args_.putString(FLAG_ARG, flag);
            return this;
        }

        public ImageSelectFragment_.FragmentBuilder_ uri(String uri) {
            args_.putString(URI_ARG, uri);
            return this;
        }

        public ImageSelectFragment_.FragmentBuilder_ subject(String subject) {
            args_.putString(SUBJECT_ARG, subject);
            return this;
        }

        public ImageSelectFragment_.FragmentBuilder_ study(String study) {
            args_.putString(STUDY_ARG, study);
            return this;
        }

    }

}
