//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package kr.ewhapp.kjw.handy.study;

import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.TextView;
import kr.ewhapp.handy.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ResultFragment_
    extends ResultFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;
    public final static String SUBJECT_ARG = "subject";
    public final static String STUDY_ARG = "study";
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.layout_result, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectFragmentArguments_();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ResultFragment_.FragmentBuilder_ builder() {
        return new ResultFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        subjectNameTv = ((TextView) hasViews.findViewById(kr.ewhapp.handy.R.id.subject_name_tv));
        studyNameTv = ((TextView) hasViews.findViewById(kr.ewhapp.handy.R.id.study_name_tv));
        subjectCountTv = ((TextView) hasViews.findViewById(kr.ewhapp.handy.R.id.subject_count_tv));
        studyCountTv = ((TextView) hasViews.findViewById(kr.ewhapp.handy.R.id.study_count_tv));
        {
            View view = hasViews.findViewById(kr.ewhapp.handy.R.id.result_main_btn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ResultFragment_.this.replaceTimeline();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(kr.ewhapp.handy.R.id.result_ok_btn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ResultFragment_.this.replaceSubject();
                    }

                }
                );
            }
        }
        init();
    }

    private void injectFragmentArguments_() {
        Bundle args_ = getArguments();
        if (args_!= null) {
            if (args_.containsKey(SUBJECT_ARG)) {
                subject = args_.getString(SUBJECT_ARG);
            }
            if (args_.containsKey(STUDY_ARG)) {
                study = args_.getString(STUDY_ARG);
            }
        }
    }

    @Override
    public void setStudyScore(final StudyModel data) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ResultFragment_.super.setStudyScore(data);
            }

        }
        );
    }

    @Override
    public void setTotalScore(final StudyModel data) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ResultFragment_.super.setTotalScore(data);
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public ResultFragment build() {
            ResultFragment_ fragment_ = new ResultFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

        public ResultFragment_.FragmentBuilder_ subject(String subject) {
            args_.putString(SUBJECT_ARG, subject);
            return this;
        }

        public ResultFragment_.FragmentBuilder_ study(String study) {
            args_.putString(STUDY_ARG, study);
            return this;
        }

    }

}
